### ISSUE TITLE
How do you test the extension?

### ISSUE THREAD

**Issue by leekelleher** [KevinJump/UmbSense#12]
Hi @KevinJump,

When I added in some of the other directives, I was following by example. I couldn't figure out how to actually test it out within Visual Studio.

So how do you test it out? Is it a case of dropping the DLLs in a specific folder location?

Thanks.

**Comment by KevinJump** [comment]
When you debug it, it runs a new instance of vs up. (can't remember if i had to configure something ... will go look). 

![image](https://user-images.githubusercontent.com/431231/67902612-7a135e80-fb61-11e9-8b9d-de15ea2d4ca5.png)

**Comment by leekelleher** [comment]
Cool, that's all I needed to know. Didn't think to push that button! 🤦‍♂
