### ISSUE TITLE
Add items from the todo list. 

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/UmbSense#24]
Umb sense offers intellisene for Umbraco tags. 

We are working through the [todo.md](https://github.com/KevinJump/UmbSense/blob/master/TODO.md) list 

- the docs are a good place to work out what a tag does. 
https://our.umbraco.com/apidocs/v8/ui/#/api

- but sometimes you have to search the Umbraco source (https://github.com/umbraco/Umbraco-CMS)   - tip is search for tag camelCase (e.g for umb-button search for umbButton)

**Comment by adam-werner** [comment]
I do see in another listed issue that there's a possible initiative of using looking at ngDocs to potentially build some of this out and I'm interested and doing a little investigated, but if there's no objection I'll continue to contribute what I can from the [todo.md](https://github.com/KevinJump/UmbSense/blob/master/TODO.md)

**Comment by leekelleher** [comment]
Now v1.4 is released, the (current) to-do list is done! 🎉

**Comment by KevinJump** [comment]
indeed!
